inputSet:
  name: Build_Oyyou_EphemeralEnvironments_API_1702470556171-push-trigger-input-set
  identifier: Build_Oyyou_EphemeralEnvironments_API_1702470556171pushtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_Oyyou_EphemeralEnvironments_API_1702470556171
    properties:
      ci:
        codebase:
          build:
            type: branch
            spec:
              branch: <+trigger.branch>
