inputSet:
  name: Build_Oyyou_EphemeralEnvironments_API_1702468795755-pr-trigger-input-set
  identifier: Build_Oyyou_EphemeralEnvironments_API_1702468795755prtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_Oyyou_EphemeralEnvironments_API_1702468795755
    properties:
      ci:
        codebase:
          build:
            type: PR
            spec:
              number: <+trigger.prNumber>
