version: '3.9'

services:
  ee.api:
    labels:
      shipyard.route: '/api'
    container_name: ee.api
    image: ${DOCKER_REGISTRY-}ee-api
    build:
      context: .
      dockerfile: EphemeralEnvironments.API/Dockerfile
    networks:
      - ee_net
    expose: 
      - 6050
    ports: 
      - 6050:80

networks:
  ee_net:
    external: true