pipeline:
  identifier: Build_Oyyou_EphemeralEnvironments_API_1702470556171
  name: Build EphemeralEnvironments.API
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1702470542989
        repoName: Oyyou/EphemeralEnvironments.API
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: build
                  spec:
                    shell: Sh
                    command: dotnet build
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: run
                  identifier: run
                  spec:
                    shell: Sh
                    command: dotnet run --project ./EphemeralEnvironments.API/EphemeralEnvironments.API.csproj
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
