pipeline:
  identifier: Build_Oyyou_EphemeralEnvironments_API_1702470556171
  name: Build EphemeralEnvironments.API
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1702470542989
        repoName: Oyyou/EphemeralEnvironments.API
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: build
                  spec:
                    connectorRef: <+input>
                    image: mcr.microsoft.com/dotnet/sdk:6.0
                    shell: Sh
                    command: dotnet build
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: <+input>
                    repo: oyyou/ephemeralenvironments.api
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
